apiVersion: batch/v1
kind: Job
metadata:
  name: extractor
spec:
  parallelism: 1
  template:
    metadata:
      name: extractor
    spec:
      containers:
        - name: extractor
          image: extractor
          imagePullPolicy: Never
          env:
            - name: IP
              value: minio-service
      restartPolicy: OnFailure
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: extractor
#   labels:
#     app: extractor
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: extractor
#   template:
#     metadata:
#       labels:
#         app: extractor
#     spec:
#       containers:
#         - name: extractor
#           image: extractor
#           imagePullPolicy: Never
#           env:
#             - name: IP
#               value: minio-service
#           ports:
#             - containerPort: 4000

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: extractor-service
# spec:
#   selector:
#     app: extractor
#   ports:
#     - port: 4000
#       targetPort: 4000
